"""不依赖具体数据库技术的 Repository 契约。"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Generic, Protocol, TypeVar

from job_agent.domain.schemas import (
    ApplicationAnswer,
    ApplicationEvent,
    ApplicationRecord,
    CandidateProfile,
    JobPosting,
    MatchResult,
    ResumeEvidence,
    ResumeVersion,
)
from job_agent.application.contracts import ResumeRecord


class RepositoryError(RuntimeError):
    """Repository 持久化操作失败。"""


class EntityNotFoundError(RepositoryError):
    """待更新实体不存在。"""


class DuplicateEntityError(RepositoryError):
    """主键或业务唯一键已存在。"""


class InvalidPaginationError(RepositoryError):
    """分页参数不合法。"""


class ImmutableFieldError(RepositoryError):
    """尝试修改不可变业务字段。"""


ItemT = TypeVar("ItemT")


@dataclass(frozen=True)
class Page(Generic[ItemT]):
    """与 ORM 无关的分页结果。"""

    items: list[ItemT]
    total: int
    limit: int
    offset: int


class CandidateRepository(Protocol):
    def add(self, entity: CandidateProfile) -> CandidateProfile: ...
    def get_by_id(self, entity_id: str) -> CandidateProfile | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Page[CandidateProfile]: ...
    def update(self, entity: CandidateProfile) -> CandidateProfile: ...
    def delete(self, entity_id: str) -> bool: ...


class ResumeEvidenceRepository(Protocol):
    def add(self, entity: ResumeEvidence) -> ResumeEvidence: ...
    def get_by_id(self, entity_id: str) -> ResumeEvidence | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Page[ResumeEvidence]: ...
    def list_by_candidate(
        self, candidate_id: str, *, limit: int = 50, offset: int = 0
    ) -> Page[ResumeEvidence]: ...
    def list_verified_by_candidate(
        self, candidate_id: str, *, limit: int = 50, offset: int = 0
    ) -> Page[ResumeEvidence]: ...
    def update(self, entity: ResumeEvidence) -> ResumeEvidence: ...
    def delete(self, entity_id: str) -> bool: ...


class ResumeRepository(Protocol):
    def add(self, entity: ResumeRecord) -> ResumeRecord: ...
    def get_by_id(self, entity_id: str) -> ResumeRecord | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Page[ResumeRecord]: ...
    def update(self, entity: ResumeRecord) -> ResumeRecord: ...
    def upsert(self, entity: ResumeRecord) -> ResumeRecord: ...
    def delete(self, entity_id: str) -> bool: ...


class JobRepository(Protocol):
    def add(self, entity: JobPosting) -> JobPosting: ...
    def get_by_id(self, entity_id: str) -> JobPosting | None: ...
    def get_by_fingerprint(self, fingerprint: str) -> JobPosting | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Page[JobPosting]: ...
    def update(self, entity: JobPosting) -> JobPosting: ...
    def upsert(self, entity: JobPosting) -> JobPosting: ...
    def delete(self, entity_id: str) -> bool: ...


class MatchRepository(Protocol):
    def add(self, entity: MatchResult) -> MatchResult: ...
    def get_by_id(self, entity_id: str) -> MatchResult | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Page[MatchResult]: ...
    def update(self, entity: MatchResult) -> MatchResult: ...
    def upsert(self, entity: MatchResult) -> MatchResult: ...
    def delete(self, entity_id: str) -> bool: ...


class ResumeVersionRepository(Protocol):
    def add(self, entity: ResumeVersion) -> ResumeVersion: ...
    def get_by_id(self, entity_id: str) -> ResumeVersion | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Page[ResumeVersion]: ...
    def update(self, entity: ResumeVersion) -> ResumeVersion: ...
    def delete(self, entity_id: str) -> bool: ...


class ApplicationRepository(Protocol):
    def add(self, entity: ApplicationRecord) -> ApplicationRecord: ...
    def get_by_id(self, entity_id: str) -> ApplicationRecord | None: ...
    def list(self, *, limit: int = 50, offset: int = 0) -> Page[ApplicationRecord]: ...
    def update(self, entity: ApplicationRecord) -> ApplicationRecord: ...
    def upsert(self, entity: ApplicationRecord) -> ApplicationRecord: ...
    def delete(self, entity_id: str) -> bool: ...
    def add_answer(self, entity: ApplicationAnswer) -> ApplicationAnswer: ...
    def list_answers(
        self, application_id: str, *, limit: int = 50, offset: int = 0
    ) -> Page[ApplicationAnswer]: ...
    def append_event(self, entity: ApplicationEvent) -> ApplicationEvent: ...
    def list_events(
        self, application_id: str, *, limit: int = 50, offset: int = 0
    ) -> Page[ApplicationEvent]: ...
